# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metrics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'metrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmetrics.proto\x12\robservability\x1a\x0c\x63ommon.proto\"\xa0\x01\n\x12\x44\x65viceHardwareInfo\x12\x16\n\x0ephysical_cores\x18\x01 \x01(\r\x12\x14\n\x0clogical_cpus\x18\x02 \x01(\r\x12\x13\n\x0bl1_cache_kb\x18\x03 \x01(\r\x12\x13\n\x0bl2_cache_kb\x18\x04 \x01(\r\x12\x13\n\x0bl3_cache_kb\x18\x05 \x01(\r\x12\x1d\n\x15total_physical_memory\x18\x06 \x01(\x04\"9\n\x0bMetricBatch\x12*\n\x06points\x18\x01 \x03(\x0b\x32\x1a.observability.MetricPoint\"\xec\x01\n\x0bMetricPoint\x12\x1b\n\x13\x63lient_timestamp_ms\x18\x01 \x01(\x04\x12\x30\n\x0cnetwork_type\x18\x02 \x01(\x0e\x32\x1a.observability.NetworkType\x12\x1d\n\x15\x62\x61ttery_level_percent\x18\x03 \x01(\x02\x12*\n\x03\x63pu\x18\x04 \x01(\x0b\x32\x18.observability.CpuDetailH\x00\x88\x01\x01\x12\x30\n\x06memory\x18\x05 \x01(\x0b\x32\x1b.observability.MemoryDetailH\x01\x88\x01\x01\x42\x06\n\x04_cpuB\t\n\x07_memory\"D\n\tCpuDetail\x12\x1b\n\x13total_usage_percent\x18\x01 \x01(\x02\x12\x1a\n\x12\x63ore_usage_percent\x18\x02 \x03(\x02\"\xb8\x01\n\x0cMemoryDetail\x12\x1a\n\x12\x61pp_resident_bytes\x18\x01 \x01(\x04\x12\x19\n\x11\x61pp_virtual_bytes\x18\x02 \x01(\x04\x12\x19\n\x11system_free_bytes\x18\x03 \x01(\x04\x12\x1b\n\x13system_active_bytes\x18\x04 \x01(\x04\x12\x1d\n\x15system_inactive_bytes\x18\x05 \x01(\x04\x12\x1a\n\x12system_wired_bytes\x18\x06 \x01(\x04\x42@Z>github.com/threatfabric-devops/tf-telemetry/internal/gen/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/threatfabric-devops/tf-telemetry/internal/gen/pb;pb'
  _globals['_DEVICEHARDWAREINFO']._serialized_start=47
  _globals['_DEVICEHARDWAREINFO']._serialized_end=207
  _globals['_METRICBATCH']._serialized_start=209
  _globals['_METRICBATCH']._serialized_end=266
  _globals['_METRICPOINT']._serialized_start=269
  _globals['_METRICPOINT']._serialized_end=505
  _globals['_CPUDETAIL']._serialized_start=507
  _globals['_CPUDETAIL']._serialized_end=575
  _globals['_MEMORYDETAIL']._serialized_start=578
  _globals['_MEMORYDETAIL']._serialized_end=762
# @@protoc_insertion_point(module_scope)
