// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: internal/observability/observability.proto

package observability

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ObservabilityService_SubmitMetrics_FullMethodName = "/observability.ObservabilityService/SubmitMetrics"
	ObservabilityService_SubmitLogs_FullMethodName    = "/observability.ObservabilityService/SubmitLogs"
)

// ObservabilityServiceClient is the client API for ObservabilityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// --- Service Definition ---
type ObservabilityServiceClient interface {
	SubmitMetrics(ctx context.Context, in *MetricBatch, opts ...grpc.CallOption) (*Ack, error)
	SubmitLogs(ctx context.Context, in *LogBatch, opts ...grpc.CallOption) (*Ack, error)
}

type observabilityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewObservabilityServiceClient(cc grpc.ClientConnInterface) ObservabilityServiceClient {
	return &observabilityServiceClient{cc}
}

func (c *observabilityServiceClient) SubmitMetrics(ctx context.Context, in *MetricBatch, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ObservabilityService_SubmitMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observabilityServiceClient) SubmitLogs(ctx context.Context, in *LogBatch, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ObservabilityService_SubmitLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObservabilityServiceServer is the server API for ObservabilityService service.
// All implementations must embed UnimplementedObservabilityServiceServer
// for forward compatibility.
//
// --- Service Definition ---
type ObservabilityServiceServer interface {
	SubmitMetrics(context.Context, *MetricBatch) (*Ack, error)
	SubmitLogs(context.Context, *LogBatch) (*Ack, error)
	mustEmbedUnimplementedObservabilityServiceServer()
}

// UnimplementedObservabilityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedObservabilityServiceServer struct{}

func (UnimplementedObservabilityServiceServer) SubmitMetrics(context.Context, *MetricBatch) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitMetrics not implemented")
}
func (UnimplementedObservabilityServiceServer) SubmitLogs(context.Context, *LogBatch) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitLogs not implemented")
}
func (UnimplementedObservabilityServiceServer) mustEmbedUnimplementedObservabilityServiceServer() {}
func (UnimplementedObservabilityServiceServer) testEmbeddedByValue()                              {}

// UnsafeObservabilityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObservabilityServiceServer will
// result in compilation errors.
type UnsafeObservabilityServiceServer interface {
	mustEmbedUnimplementedObservabilityServiceServer()
}

func RegisterObservabilityServiceServer(s grpc.ServiceRegistrar, srv ObservabilityServiceServer) {
	// If the following call panics, it indicates UnimplementedObservabilityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ObservabilityService_ServiceDesc, srv)
}

func _ObservabilityService_SubmitMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservabilityServiceServer).SubmitMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObservabilityService_SubmitMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservabilityServiceServer).SubmitMetrics(ctx, req.(*MetricBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObservabilityService_SubmitLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservabilityServiceServer).SubmitLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObservabilityService_SubmitLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservabilityServiceServer).SubmitLogs(ctx, req.(*LogBatch))
	}
	return interceptor(ctx, in, info, handler)
}

// ObservabilityService_ServiceDesc is the grpc.ServiceDesc for ObservabilityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObservabilityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "observability.ObservabilityService",
	HandlerType: (*ObservabilityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitMetrics",
			Handler:    _ObservabilityService_SubmitMetrics_Handler,
		},
		{
			MethodName: "SubmitLogs",
			Handler:    _ObservabilityService_SubmitLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/observability/observability.proto",
}
