# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'logs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nlogs.proto\x12\robservability\x1a\x0c\x63ommon.proto\"4\n\x08LogBatch\x12(\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x17.observability.LogEntry\"\xb0\x02\n\x08LogEntry\x12\x1b\n\x13\x63lient_timestamp_ms\x18\x01 \x01(\x04\x12\x30\n\x0cnetwork_type\x18\x02 \x01(\x0e\x32\x1a.observability.NetworkType\x12&\n\x05level\x18\x03 \x01(\x0e\x32\x17.observability.LogLevel\x12\x0b\n\x03tag\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t\x12\x35\n\x07\x63ontext\x18\x06 \x03(\x0b\x32$.observability.LogEntry.ContextEntry\x12\x18\n\x0bstack_trace\x18\x07 \x01(\tH\x00\x88\x01\x01\x1a.\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x0e\n\x0c_stack_trace*?\n\x08LogLevel\x12\t\n\x05\x44\x45\x42UG\x10\x00\x12\x08\n\x04INFO\x10\x01\x12\x08\n\x04WARN\x10\x02\x12\t\n\x05\x45RROR\x10\x03\x12\t\n\x05\x46\x41TAL\x10\x04\x42\x36Z4github.com/minhtt159/tf-telemetry/internal/gen/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/minhtt159/tf-telemetry/internal/gen/pb;pb'
  _globals['_LOGENTRY_CONTEXTENTRY']._loaded_options = None
  _globals['_LOGENTRY_CONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_LOGLEVEL']._serialized_start=404
  _globals['_LOGLEVEL']._serialized_end=467
  _globals['_LOGBATCH']._serialized_start=43
  _globals['_LOGBATCH']._serialized_end=95
  _globals['_LOGENTRY']._serialized_start=98
  _globals['_LOGENTRY']._serialized_end=402
  _globals['_LOGENTRY_CONTEXTENTRY']._serialized_start=340
  _globals['_LOGENTRY_CONTEXTENTRY']._serialized_end=386
# @@protoc_insertion_point(module_scope)
