# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import metrics_pb2 as metrics__pb2
import logs_pb2 as logs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\robservability\x1a\x0c\x63ommon.proto\x1a\rmetrics.proto\x1a\nlogs.proto\"\'\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xcd\x01\n\x0fTelemetryPacket\x12\x16\n\x0eschema_version\x18\x01 \x01(\r\x12/\n\x08metadata\x18\x02 \x01(\x0b\x32\x1d.observability.ClientMetadata\x12\x30\n\x07metrics\x18\x03 \x01(\x0b\x32\x1a.observability.MetricBatchH\x00\x88\x01\x01\x12*\n\x04logs\x18\x04 \x01(\x0b\x32\x17.observability.LogBatchH\x01\x88\x01\x01\x42\n\n\x08_metricsB\x07\n\x05_logs\"\xb7\x02\n\x0e\x43lientMetadata\x12)\n\x08platform\x18\x01 \x01(\x0e\x32\x17.observability.Platform\x12\x1c\n\x0finstallation_id\x18\x02 \x01(\x0cH\x00\x88\x01\x01\x12\x17\n\njourney_id\x18\x03 \x01(\x0cH\x01\x88\x01\x01\x12\x1a\n\x12sdk_version_packed\x18\x04 \x01(\r\x12\x18\n\x10host_app_version\x18\x05 \x01(\t\x12\x15\n\rhost_app_name\x18\x06 \x01(\t\x12?\n\x0f\x64\x65vice_hardware\x18\x07 \x01(\x0b\x32!.observability.DeviceHardwareInfoH\x02\x88\x01\x01\x42\x12\n\x10_installation_idB\r\n\x0b_journey_idB\x12\n\x10_device_hardware2P\n\tCollector\x12\x43\n\rSendTelemetry\x12\x1e.observability.TelemetryPacket\x1a\x12.observability.AckB@Z>github.com/threatfabric-devops/tf-telemetry/internal/gen/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/threatfabric-devops/tf-telemetry/internal/gen/pb;pb'
  _globals['_ACK']._serialized_start=75
  _globals['_ACK']._serialized_end=114
  _globals['_TELEMETRYPACKET']._serialized_start=117
  _globals['_TELEMETRYPACKET']._serialized_end=322
  _globals['_CLIENTMETADATA']._serialized_start=325
  _globals['_CLIENTMETADATA']._serialized_end=636
  _globals['_COLLECTOR']._serialized_start=638
  _globals['_COLLECTOR']._serialized_end=718
# @@protoc_insertion_point(module_scope)
